version: "3.8"

services:
  postgresdb:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgres
  app:
    build: .
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  db:
